name: "09 - Using Functions"

on: 
    pull_request:
      types:
        - opened
        - closed
      branches:
        - main
    workflow_dispatch:
        
jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Print PR Title
              env: 
                TITLE: ${{ github.event.pull_request.title }}
              run: | 
                echo "Title of pull request: $TITLE"

            - name: Print PR Labels 
              run: | 
                cat << EOF 
                ${{ toJson(github.event.pull_request.labels) }}
                EOF

            - name: Bug step
              if: ${{ failure() && contains(github.event.pull_request.labels.*.name, 'fix') }}
              run: |
                echo "I am a bug fix."

            - name: Sleep for 20 seconds
              run: | 
                echo "Sleep 20"
                
            - name: Failing Step 
              run: | 
                exit 1

            - name: I will be skipped 
              if: ${{ success() }}
              run: | 
                echo "I will print if previous steps succeed"

            - name: I will execute 
              if: ${{ failure() }}
              run: | 
                echo "I will print if any previous step fails."

            - name: I will execute
              if: ${{ !cancelled() }}
              run: | 
                echo "I will always print, except when the workflow is cancelled."

            - name: I will execute when cancelled
              if: ${{ cancelled() }}
              run: | 
                echo "I will print when the workflow has been cancelled."

            
